### ISSUE TITLE
Name should be checked more carefully in profile :)

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#10]
Right now it can be infinite, and even contains non-regular characters 

See : 

![image](https://user-images.githubusercontent.com/3889245/39188287-b7ec564a-47cf-11e8-9505-993f66e0ea17.png)

**Comment by dyoann** [comment]
Same applies for "Nickname" below

**Comment by DomantasP** [comment]
Fixed it. Fix will be available with the next test platform update.
