### ISSUE TITLE
[Verify Claim] Display messages as notifications then they will be more readable

### ISSUE THREAD

**Issue by dariusdev** [AigangNetwork/aigang-platform-web#106]
![image](https://user-images.githubusercontent.com/6444878/44513121-2d163b80-a6c5-11e8-9121-55364b618aed.png)

**Comment by dariusdev** [comment]
Display message that: We detected your broken device. You can Claim your policy

**Comment by zilvinasjuc** [comment]
![image](https://user-images.githubusercontent.com/15123903/44656168-87363a00-aa00-11e8-80b0-165f8b88c4b7.png)
