### ISSUE TITLE
When i register new phone it shows device Age 0 months and cant get insurance.

### ISSUE THREAD

**Issue by dariusdev** [AigangNetwork/aigang-platform-web#121]
Need to fix that

**Comment by zilvinasjuc** [comment]
Changed to return 1 when calculated device age is zero

**Comment by zilvinasjuc** [comment]
New apk version: https://github.com/AigangNetwork/aigang-insurance-app/commit/de8de1498697c8683dcfdcf837711dfdc4db5872
