### ISSUE TITLE
Weird update unsync

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#13]
Steps to reproduce : 

1) Login
2 ) go to /profile
3) Click on change, type anything on any of the 3 fields (memorize the old value) 
 ->  the UI shows the new value(s)
4) Refresh page (or F5) 
 ->  there is a bug, it shows the old value(s) !
5) Logout / Login -> we see the new value was set ... so there is some synchronization problem

**Comment by DomantasP** [comment]
Fixed it. Fix will be available with the next test platform update.

**Comment by dyoann** [comment]
Thanks for fixing these :) 
Any possibility to test more features ?
I see there was some models stuff in code 
but I don’t see it in UI . Does this need some special account ? Thanks

**Comment by adasiunas** [comment]
Yes @dyoann you are right, models are implemented on our local environment. You will be able to test it as soon as we will deploy them to the QA environment.

**Comment by dyoann** [comment]
Any idea when the new QA update will be release ?
People in telegram are worried there is no monthly update by the CEO , if he is busy you could just say in telegram  a quick summary of what you did this month ? That would be nice ! ( it’s not for me I know how to read a GitHub , it’s for regular non geek investors )

**Comment by adasiunas** [comment]
QA environment is updated, you can test new features if you want to.

**Comment by dyoann** [comment]
Thanks , will do .
