### ISSUE TITLE
Remove emails from auth process

### ISSUE THREAD

**Issue by xhipster** [AigangNetwork/aigang-platform-web#131]
Please, make them optional for notifications only

**Comment by dariusdev** [comment]
Please be more specific what emails and from where? When you log in you are getting an email?

**Comment by xhipster** [comment]
I mean this: https://aigang.network/login
My default behavior that if I see that some app claim it is dapp and for any interaction it asks email I am leaving this app as fraudulent. There are a lot of Web3 libs around just for that

**Comment by dariusdev** [comment]
Email is a stable tempory solution until we will have a reliable login system in ethereum ecosystem. We will integrate them when they will be fully developed.

**Comment by dariusdev** [comment]
yep we already have this feature request registered:
https://github.com/AigangNetwork/aigang-platform-web/issues/126

**Comment by xhipster** [comment]
Great. Will track it. 

Keep in mind that I am personally is not going to use aigang apps until it wont follow web3 principles. I donated to a project on presale because there were some promises in terms of decentralization. Would not love to see initial release based on email logins after year of development. Definitely will dump AIX without any hesitation even though I still do believe in a bright future of the project.

**Comment by dariusdev** [comment]
👍  This is your decision to do something or not :)
