### ISSUE TITLE
transaction error

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#149]
I tried to invest 128 AIX  (fake one of course) in the pool there:
https://testplatform.aigang.network/pools/products/912ec803b2ce49e4a541068d495ab574

The transaction seems to have failed, for some reasons, see : https://ropsten.etherscan.io/tx/0x7dd594173f44337d8fe76b28e0f5cb75aae783d8bdc7a2b5b11619bda50be7b4

Then I got this message :
![image](https://user-images.githubusercontent.com/3889245/49804163-2e41a600-fd52-11e8-8f1d-78a26c35c72f.png)

The Current Amount shows 2500/ 250 so it seems it has counted it  (122+128 = 250)
Also it shows 9 contributors, while it was 8 before ...

**Comment by DomantasP** [comment]
We were testing this pool and closed it in the smart contract, but pool status was not changed in the database when you were trying to do contribution. Things like these can happen a lot in the testplatform, cause we are constantly tweaking and changing things, to see if everything works correctly.
