### ISSUE TITLE
Upload datasets

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#15]
This is probably due to ongoing dev, but anyway :
- "CSV file requirements" => Points to https://testplatform.aigang.network/data/upload 
- "Remote access point" doesn't seem to upload anything at the moment
(I tried some random CSV online, such as : 
https://raw.githubusercontent.com/openmundi/world.csv/master/countries(204)_olympics.csv
)

**Comment by dyoann** [comment]
In fact remote access point does something , however why not showing the CSV preview since it can be downloaded on your server ? 

https://testplatform.aigang.network/data/c7b3eca2639f4df88bd2e2d5d20a20ff/data

![image](https://user-images.githubusercontent.com/3889245/39614829-071d767c-4f73-11e8-8da8-c8b59b977822.png)

Also there is encoding issues in the "structure field" and if you edit and save once (which is triggered by enter now ...), it doesn't go back, and further saving doesn't work, to reproduce:

1) Go https://testplatform.aigang.network/data/edit/c7b3eca2639f4df88bd2e2d5d20a20ff
(or maybe one of dataset you own instead)
2) Click save once => notification that it was saved (but it doesn't go back)
3) Click save another time (or more) => nothing, and it doesn't save

**Comment by adasiunas** [comment]
1. We have fixed issue with "CSV file requirements" redirection.
2. Regarding Remote access point: 
    As specified in our documentation: 
> This field is for describing detailed steps how platform users will be able to access data file and download it. Usually it is set when provided file is too large or contains other extension than .csv

Thus, it means that dataset owner is in charge to provide brief steps how users would be able to access this dataset. API is not supposed to download or upload anything.

Encoding issue should be solved with: https://github.com/AigangNetwork/aigang-platform-web/issues/29 

Fix for saving on enter will be applied as well.
