### ISSUE TITLE
Bug payment information stuck

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#150]
1) Clicked on : https://testplatform.aigang.network/pools/products/10

2) Entered the max I could invest (I've 1000 fake AIX balance)

3) Infinite stuck on this message (and metamask is not triggered)
![image](https://user-images.githubusercontent.com/3889245/49804578-2b938080-fd53-11e8-9780-71c0fc8a7e2a.png)

**Comment by dariusdev** [comment]
This is not valid contract address configured for pool. Metamask just dont do nothing. This should be solved using only valid pools
