### ISSUE TITLE
Reddit plugin

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#151]
Up and Down arrow are not implemented yet (does nothing)

![image](https://user-images.githubusercontent.com/3889245/49804734-a8265f00-fd53-11e8-9779-0537e7c4d3f2.png)

**Comment by dyoann** [comment]
Also the number of points seems to be different than the one shown on Reddit.
For instance the "9 points" on https://www.reddit.com/r/AigangNetwork/comments/9ciss0/aigang_dev_update_julyaugust_2018_development/ is shown as "6 points" in the aigang interface

**Comment by dariusdev** [comment]
This is embedded Reddit version and we are using it as it is. Like and coin marke cap is using (https://coinmarketcap.com/currencies/aigang/#social). Please register issue for Reddit.
