### ISSUE TITLE
Error while uploading

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#16]
Could be because I'm not allowed to upload, but with a random CSV I get : 

![image](https://user-images.githubusercontent.com/3889245/39510943-e423f8e0-4deb-11e8-91b0-8844b172a393.png)

And in the console : 

![image](https://user-images.githubusercontent.com/3889245/39510905-b4a6cd18-4deb-11e8-9362-813f24657696.png)

The CSV I used : 
![image](https://user-images.githubusercontent.com/3889245/39510930-d5a7d656-4deb-11e8-93f9-8bf359f527f0.png)

**Comment by dariusdev** [comment]
Backend accepted only text/csv content type. More content types was added like text/csv-x and others.

**Comment by dyoann** [comment]
👍  Good
