### ISSUE TITLE
Content moderation for models (and maybe others parts where Vue MarkDown is used)

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#20]
With the ability to use Vue MarkDown which enables the user to link pictures (or type HTML) that could be a little supiscious, I suggest you use moderation before showing up the page to the public, no ?

For instance, I upload this model : 
![image](https://user-images.githubusercontent.com/3889245/39512134-11137cdc-4df0-11e8-9b11-7003a70283bb.png)

**Comment by dyoann** [comment]
I'm opening that one because I'm afraid angry guy at the project might link random p0rn or bad pictures to it :-) Be careful !

**Comment by dyoann** [comment]
(Notice also that my random moon image is wider than the div ! )

**Comment by adasiunas** [comment]
I'm trying to reproduce your issue, could you provide us with clear steps, how you managed to upload the image to this dataset? Or better, provide dataset id which contains this description.
Thanks

**Comment by dyoann** [comment]
I uploaded a new one here :  
https://testplatform.aigang.network/data/c7b3eca2639f4df88bd2e2d5d20a20ff

Syntax is taken from VueMarkDown documentation, which is here : 
![Moon](https://static.fjcdn.com/pictures/Soon+moon+dont+look+at+tags+nothing+to+see+there_f41eb1_3663775.jpg)

**Comment by dyoann** [comment]
lol github is also compatible with this syntax

**Comment by adasiunas** [comment]
We decided to let users provide images about the dataset. Currently, we approving Datasets manually, thus we will be checking if it does not contain any irrelevant or private data, images etc.

**Comment by dyoann** [comment]
Of course, that is ok if you block the editing by URL of non approved dataset, as seen in #23 (for example)
