### ISSUE TITLE
Models columns size / Content size

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#22]
I know I've opened things similar in the past for other fields :-) 
Maybe a non infinite limit would be good

( I also tried to put VueMardown or HTML in the table, it seems ok it's not interpreted :P ) !

![image](https://user-images.githubusercontent.com/3889245/39512679-206dd504-4df2-11e8-948d-37ca77d85d39.png)

**Comment by dariusdev** [comment]
Currently, we think that this is not an issue and will leave it as it is because this data is taken from users CSV file and it is not hiding and you have the ability to scroll to the end.

**Comment by dariusdev** [comment]
Fixed
