### ISSUE TITLE
Enter key(s) in edit view trigger save !

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#25]
This is very annoying if you want to update the model :) 

Reproduce : 
https://testplatform.aigang.network/data/fab19752ea95464bb770871bd2de83c8/models/85c18329d721496c94aaae4051b8fde8/edit

Click enter anywhere

**Comment by dyoann** [comment]
Same issue on data : 
https://testplatform.aigang.network/data/edit/c36ad8690cb7462286948da2ef152a18/

(If you want to add a new line in description, you can't with that save being triggered)

**Comment by DomantasP** [comment]
Fixed
