### ISSUE TITLE
CORS when uploading dataset

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#26]
Tried re-uploading some dataset that was already there (so I'm sure the format was ok ... )

Get classic No 'Access-Control-Allow-Origin' header is present on the requested resource error :-)

See: 
![image](https://user-images.githubusercontent.com/3889245/39516048-0e33911c-4dfc-11e8-826a-d2bc16cc7955.png)

**Comment by dariusdev** [comment]
This error occurs when you run an application on localhost and try to reach test API?
In this case, we have 2 solutions:
1) On Developers tools-> Network tab failed request response you should see the CAPTCHA. Solving it will allow you continue to work
2) You send to frequent requests to API and our firewall gives bad IP reputation. You can wait some time and continue or contact me and i will whitelist your IP

**Comment by dyoann** [comment]
No it happened on the test platform ( not localhost )  :-) I’ll check network tab next time it happens, I was hardcore testing indeed maybe blocked ! I tried uploading a CSV after you added more csv type and it worked this time

**Comment by dariusdev** [comment]
Ok. then it easier we will revise our servers IPs

**Comment by dariusdev** [comment]
All IPs are whitelisted. If you continue to receive this forbidden captcha please solve the captcha or wait some time.
