### ISSUE TITLE
Toogle Remote Access Point ON/OFF 

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#30]
Steps to reproduce bug:

1° Drop any CSV  (should be visible in the bottom in picture like this image)
![image](https://user-images.githubusercontent.com/3889245/39615146-d72e6d16-4f74-11e8-89d3-753ca010c662.png)

2° Toogle Remote access point ON and OFF , we can see then that the label disappeared, so
we might think that no more file are currently selected/uploaded 

![image](https://user-images.githubusercontent.com/3889245/39615179-1359982e-4f75-11e8-8a55-85b96aad44a5.png)

3° However, continue button works, and it shows the previously selected file (before toogling ON/OFF)

So to fix, just put the label back (or reset the field when you toogle ON/OFF completely ?)

**Comment by adasiunas** [comment]
Issue is related to https://github.com/AigangNetwork/aigang-platform-web/issues/17
