### ISSUE TITLE
Legend for dataset state

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#46]
I suggest (if possible) to add somewhere a visible legend for the state of the dataset.
For instance something like that : 

![image](https://user-images.githubusercontent.com/3889245/40234315-ab1eca3a-5aa6-11e8-8175-a2f1f464d15a.png)

Also what's the meaning of "closed" dataset ? It means we cannot edit it  or upload a new model to it ?

**Comment by adasiunas** [comment]
Hi, @dyoann, instead of creating agenda we decided to use our documentation page. https://aigang.readthedocs.io/en/latest/platform/data.html#data-set-state

**Comment by dyoann** [comment]
Ok that’s good enough .
Thanks .
