### ISSUE TITLE
The warning message should be dynamic if it's too short on input fields

### ISSUE THREAD

**Issue by dariusdev** [AigangNetwork/aigang-platform-web#6]
![image](https://user-images.githubusercontent.com/6444878/38660625-93e19352-3e36-11e8-8287-5021913a79b1.png)

Founder: dyoann

**Comment by dyoann** [comment]
![image](https://user-images.githubusercontent.com/3889245/39188139-508f68de-47cf-11e8-8712-6ed1d6659c8e.png)

Same remark for password

**Comment by dyoann** [comment]
![image](https://user-images.githubusercontent.com/3889245/39189180-e99167ba-47d1-11e8-8db6-ce5b46e30a6b.png)

Same remark for nickname

**Comment by DomantasP** [comment]
All input fields are being validate when they lose focus (on blur). It's a pretty common UI practice and we aren't sure if it's a good idea to validate after every change in the input field.
