### ISSUE TITLE
The page you are trying to access is not available bug

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#69]
I  noticed that if you stop the navigator (very quickly) from loading when accessing a forbidden URL
(i.e. the one that lead to a "The page you are trying to access it not available"), you can still see
the page , for example, I checkout the branch product-list , and the path /insurance/products/1
gives this "the page ..." warning, however if I stop the page loading, I can still see a quick preview :-) 

See below : 

![image](https://user-images.githubusercontent.com/3889245/41915434-ff62202e-7955-11e8-8466-818d712e38ee.png)

I suppose it's the same for all other pages that shows that message, unfortunately.

**Comment by DomantasP** [comment]
Until the back-end returns 401 (unauthorized error code) we are showing skeleton of the page and a loader, but we aren't showing any actual information. Maybe we will make it look differently in the future, but it's a UX thing and UX can always be improved, so I am closing this issue.

**Comment by dyoann** [comment]
Could be tagged as enhancement then ? :-)
