### ISSUE TITLE
To production

### ISSUE THREAD

**Issue by dariusdev** [AigangNetwork/aigang-platform-web#77]
Database:
- [x] Create  db users for listeners and other servises with right permissions.
- [x] Install DB scripts,  
- [x] Update DB Scripts sources.

Blockchain:
- Create executor wallets:
- - [x] Pools (balance 0 not used).
- - [x] Predictions (balance used for resolve )..
- - [x] Insurance (balance used for addClaim,AddPolicy )..
- [x] Fill executor wallet balance.
- [x] Check configuration wallets.

Services:
-  Contracts Executor 
- - [x] Add Config transformations 
- - [x] Add keys from wallets
- - [x] Create Azure service, 
- - [x] Set Azure properties, 
- - [x] Deploy , 
- - [x] merge to the production branch
- - [x] configure cloudflare
- Transactions Listener
- - [x] Add Config transformations 
- - [x] Create Azure service, 
- - [x] Set Azure properties, 
- - [x] Deploy , 
- - [x] merge to the production branch
-  Policies Listener
- - [x] Add Config transformations 
- - [x] Create Azure service, 
- - [x] Set Azure properties, 
- - [x] Deploy , 
- - [x] merge to the production branch
-  Pools listener
- - [x] Add Config transformations 
- - [x] Create Azure service, 
- - [x] Set Azure properties, 
- - [x] Deploy , 
- - [x] merge to the production branch
-  Predictions listener
- - [x] Add Config transformations 
- - [x] Create Azure service, 
- - [x] Set Azure properties, 
- - [x] Deploy , 
- - [x] merge to the production branch

API: 
- [x] Add Config transformations for Platform API
- [x] Deploy Platform API, merge to the production branch . 

WEB: 
- [x] Add Config transformations for Platform WEB
- [x] Deploy Platform WEB, merge to the production branch . 

DB: 
- [x] whitelist services IP in the DB

Insurance product:  
Configure and  Deploy Android data collector:
- - [x] Create firebase token 
- - [x] Update Config transformations 
- - [x] Create Azure service, 
- - [x] Set Azure properties, 
- - [x] Deploy , 
- - [x] merge to the production branch
- - [x] configure cloudflare

APP:  
- - [x] change App salts by Collector API
- - [x] build and deploy Android App to play store()

Test Everything

**Comment by dyoann** [comment]
Almost done ;)
