### ISSUE TITLE
In data model edit mode description should be much bigger

### ISSUE THREAD

**Issue by dariusdev** [AigangNetwork/aigang-platform-web#80]
now it is too small 
![image](https://user-images.githubusercontent.com/6444878/43781647-14b04600-9a66-11e8-91f7-1e9e0a0aa1ba.png)

**Comment by zilvinasjuc** [comment]
![image](https://user-images.githubusercontent.com/15123903/44708903-f9665780-aab0-11e8-9207-9886f3550b2c.png)
