### ISSUE TITLE
actions.js:118 Uncaught (in promise) TypeError: Cannot read property 'web3' of undefined

### ISSUE THREAD

**Issue by dariusdev** [AigangNetwork/aigang-platform-web#87]
When you refresh Products list 
![image](https://user-images.githubusercontent.com/6444878/44461717-a0af3e80-a61a-11e8-9113-a746d35d81da.png)

**Comment by dyoann** [comment]
Hello @dariusdev , when you have a stable enough version, don't hesitate I can test again like the previous time ;-)

**Comment by zilvinasjuc** [comment]
Fixed and merged o master
