### ISSUE TITLE
Random access to some pages are not blocked

### ISSUE THREAD

**Issue by dyoann** [AigangNetwork/aigang-platform-web#9]
See below :

![image](https://user-images.githubusercontent.com/3889245/39187753-661ae8e6-47ce-11e8-8378-cd749c63786e.png)

We see some error message, but it's spinning on some blured page...

**Comment by dyoann** [comment]
Seems to be linked with /data/xxx folders (works on other subdirectories)

**Comment by DomantasP** [comment]
Fixed it. Fix will be available with the next test platform update.
