### ISSUE TITLE
Message overlap

### ISSUE THREAD

**Issue by dariusdev** [AigangNetwork/aigang-platform-web#92]
![image](https://user-images.githubusercontent.com/6444878/44467852-99912c00-a62c-11e8-8030-c4bf684764f9.png)

**Comment by zilvinasjuc** [comment]
Fixed and merged to master
![image](https://user-images.githubusercontent.com/15123903/44568806-fdc50480-a780-11e8-88e4-7e50d6db77cb.png)
![image](https://user-images.githubusercontent.com/15123903/44568829-103f3e00-a781-11e8-8f83-1447c172463c.png)
