### ISSUE TITLE
Implement Paging in transactions and wallet tabs

### ISSUE THREAD

**Issue by dariusdev** [AigangNetwork/aigang-platform-web#95]

**Comment by zilvinasjuc** [comment]
![image](https://user-images.githubusercontent.com/15123903/44717630-35f07e00-aac6-11e8-9351-8e20d4f9e9fa.png)
![image](https://user-images.githubusercontent.com/15123903/44717650-46a0f400-aac6-11e8-8ebd-2723e6fb1e23.png)
